language: minimal

services:
  - docker

env:
  matrix:
    - PYTHON_VERSION=3.5 BACKEND=postgres
    - PYTHON_VERSION=3.6 BACKEND=postgres
    - PYTHON_VERSION=3.7 BACKEND=postgres
    - PYTHON_VERSION=3.5 BACKEND=azurite
    - PYTHON_VERSION=3.6 BACKEND=azurite
    - PYTHON_VERSION=3.7 BACKEND=azurite
    - PYTHON_VERSION=3.5 BACKEND=iotedge
    - PYTHON_VERSION=3.6 BACKEND=iotedge
    - PYTHON_VERSION=3.7 BACKEND=iotedge

before_install:
  - export DOCKER_IMAGE="${DOCKER_USER:-dev}/appinsights-on-premises:${TRAVIS_TAG:-dev}"
  - docker_compose() { docker-compose -f docker-compose.yml -f backends/${BACKEND}.yml $*; }

install:
  - docker_compose build

before_script:
  - export AZURITE_PORT=8889
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - export APPINSIGHTS_INSTRUMENTATIONKEY="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - docker_compose up -d

script:
  - docker_compose run app python -m app.tools.generate_telemetry --ikey "${APPINSIGHTS_INSTRUMENTATIONKEY}"

after_script:
  - docker_compose down --volumes --remove-orphans

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE}"
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
      condition: ${PYTHON_VERSION}-${BACKEND} = 3.7-postgres
