language: minimal

services:
  - docker

install:
  - docker-compose build

before_script:
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - docker-compose up -d
  - while ! nc -z localhost ${POSTGRES_PORT}; do sleep 2s; done
  - while ! nc -z localhost ${APP_PORT}; do sleep 2s; done
  - docker-compose run app python -m app.tools.create_db
  - IKEY="$(docker-compose run app python -m app.tools.register_client)"
  - export IKEY

script:
  - docker-compose run app flake8 app
  - docker-compose run app isort --quiet --check-only --recursive app
  - docker-compose run app mypy app
  - docker-compose run app python -m app.tools.generate_telemetry --ikey "${IKEY}"

after_script:
  - docker-compose down --volumes --remove-orphans

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
  - export DOCKER_IMAGE="${DOCKER_USER}/appinsights-on-premises:${TRAVIS_TAG}"
  - export DEVTOOLS=False
  - docker-compose build

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE}"
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
