language: minimal

services:
  - docker

env:
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7

before_install:
  - export DOCKER_IMAGE="${DOCKER_USER:-dev}/appinsights-on-premises:${TRAVIS_TAG:-dev}"

install:
  - docker-compose build

before_script:
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - export APPINSIGHTS_INSTRUMENTATIONKEY="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - docker-compose up -d

script:
  - docker-compose run app python -m app.tools.generate_telemetry --ikey "${APPINSIGHTS_INSTRUMENTATIONKEY}"

after_script:
  - docker-compose down --volumes --remove-orphans

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE}"
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
      condition: ${PYTHON_VERSION} = 3.7
