language: minimal

services:
  - docker

install:
  - docker-compose build

before_script:
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - export APPINSIGHTS_INSTRUMENTATIONKEY="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - docker-compose up -d

script:
  - docker-compose run app python -m app.tools.generate_telemetry --ikey "${APPINSIGHTS_INSTRUMENTATIONKEY}"

after_script:
  - docker-compose down --volumes --remove-orphans

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
  - export DOCKER_IMAGE="${DOCKER_USER}/appinsights-on-premises:${TRAVIS_TAG}"
  - docker-compose build

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE}"
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
