language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip install flake8 mypy
  - docker-compose build

before_script:
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - docker-compose up -d
  - while ! nc -z localhost ${POSTGRES_PORT}; do sleep 2s; done
  - while ! nc -z localhost ${APP_PORT}; do sleep 2s; done
  - docker-compose run app app.tools.create_db
  - IKEY="$(docker-compose run app app.tools.register_client)"
  - export IKEY

script:
  - flake8 app
  - mypy app
  - docker-compose run app app.tools.generate_telemetry --ikey "${IKEY}"

after_script:
  - docker-compose down --volumes --remove-orphans
