language: python

python:
  - 3.6
  - 3.7
  - 3.8

dist: xenial

sudo: required

services:
  - docker

env:
  matrix:
    - APP_ENV=azurite+libcloud
    - APP_ENV=iotedge+libcloud
    - APP_ENV=postgres
  global:
    - AZURITE_PORT=8889
    - POSTGRES_PORT=8888
    - APP_PORT=8080

before_install:
  - export PYTHON_VERSION="${TRAVIS_PYTHON_VERSION}"
  - export CONNECTOR="${APP_ENV#*+}"
  - export BACKEND="${APP_ENV%+*}"
  - export DOCKER_IMAGE="${DOCKER_USER:-dev}/appinsights-on-premises:${TRAVIS_TAG:-dev}-${CONNECTOR}"

install:
  - make build

before_script:
  - export IKEY1="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - export IKEY2="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - make start

script:
  - make tests

after_script:
  - make stop

deploy:
  - provider: script
    script: make release
    on:
      tags: true
      condition: ${PYTHON_VERSION} = 3.8
