language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip install -r requirements-dev.txt
  - if [[ -n "${TRAVIS_TAG}" ]]; then export DOCKER_IMAGE="${DOCKER_USER}/appinsights-on-premises:${TRAVIS_TAG}"; fi
  - docker-compose build

before_script:
  - export POSTGRES_PORT=8888
  - export APP_PORT=8080
  - docker-compose up -d
  - while ! nc -z localhost ${POSTGRES_PORT}; do sleep 2s; done
  - while ! nc -z localhost ${APP_PORT}; do sleep 2s; done
  - docker-compose run app app.tools.create_db
  - IKEY="$(docker-compose run app app.tools.register_client)"
  - export IKEY

script:
  - flake8 app
  - mypy app
  - docker-compose run app app.tools.generate_telemetry --ikey "${IKEY}"

after_script:
  - docker-compose down --volumes --remove-orphans

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE}"
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
