language: python

python:
  - 3.5
  - 3.6
  - 3.7

dist: xenial

sudo: required

services:
  - docker

env:
  matrix:
    - BACKEND=azurite
    - BACKEND=iotedge
    - BACKEND=postgres
  global:
    - AZURITE_PORT=8889
    - POSTGRES_PORT=8888
    - APP_PORT=8080

before_install:
  - export PYTHON_VERSION="${TRAVIS_PYTHON_VERSION}"
  - export DOCKER_IMAGE="${DOCKER_USER:-dev}/appinsights-on-premises:${TRAVIS_TAG:-dev}"

install:
  - make build

before_script:
  - export APPINSIGHTS_INSTRUMENTATIONKEY="$(python3 -c 'import uuid; print(uuid.uuid4())')"
  - make start

script:
  - make tests

after_script:
  - make stop

deploy:
  - provider: script
    script: make release
    on:
      repo: CatalystCode/appinsights-on-premises
      tags: true
      condition: ${PYTHON_VERSION}-${BACKEND} = 3.7-postgres
