version: "3"

services:

  app:
    image: "${DOCKER_IMAGE}"
    build:
      context: .
      args:
        PYTHON_VERSION: "${PYTHON_VERSION}"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      APP_URL: "http://app"
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    ports:
      - ${APP_PORT}:80

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - ${POSTGRES_PORT}:5432
