version: "3"

services:

  app:
    build:
      args:
        CONNECTOR: libcloud
    depends_on:
      - azurite
    environment:
      DATABASE_URL: "libcloud://${AZURITE_ACCOUNT}:${AZURITE_SECRET}@azure_blobs?endpoint=azurite:10000&ssl=False"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: ["azurite-blob", "--blobHost=0.0.0.0"]
    environment:
      AZURITE_ACCOUNTS: "${AZURITE_ACCOUNT}:${AZURITE_SECRET};"
    ports:
      - ${AZURITE_PORT}:10000
