version: "3"

services:

  app:
    image: "${DOCKER_IMAGE}"
    build:
      context: ..
      args:
        PYTHON_VERSION: "${PYTHON_VERSION}"
    environment:
      APP_URL: "http://app:8000"
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
    ports:
      - ${APP_PORT}:8000
